wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.10.9
    start_time: 1676887492.618862
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 7
      - 19
      - 23
      4: 3.10.9
      5: 0.13.10
      8:
      - 1
      - 4
      - 5
batch_size:
  desc: null
  value: 32
inp_size:
  desc: null
  value: 28
lr:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: Adam
